### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by polluks** [8bit-Dude/8bit-Unity#1]
jsr -> jmp
https://github.com/8bit-Dude/8bit-Unity/blob/816bde21ed6204f459801dab0ba0ae80aefff3b0/unity/Apple/prodos.s#L54
https://github.com/8bit-Dude/8bit-Unity/blob/816bde21ed6204f459801dab0ba0ae80aefff3b0/unity/Apple/prodos.s#L72

**Comment by 8bit-Dude** [comment]
Thanks for flagging those up Polluks.
BTW, I am not actually using these function yet, because the code does not work.
I must have made a mistake somewhere, but I can't figure out what...

**Comment by polluks** [comment]
Do you mean ProDOS? I saw your working example... :-)
See also https://github.com/8bit-Dude/8bit-Unity/blob/80b38f0877b27b9fcdc932c4547d28185f10f471/unity/Atari/xbios.s

**Comment by 8bit-Dude** [comment]
Alright, so the idea is to never have JSR just before RTS?
