### ISSUE TITLE
Background palette is not being displayed correctly on Lynx

### ISSUE THREAD

**Issue by haroldo-ok** [8bit-Dude/8bit-Unity#12]
Hello, again;

I'm having a weird problem where a background image is not being displayed correctly on Lynx, even though the image is using the same palette as the demo images:

![lectureh-lynx](https://user-images.githubusercontent.com/1457465/103315916-c0827880-4a05-11eb-9f61-73d068af99de.png)

When running the application on Lynx, the image above is displayed with the wrong palette:

![image](https://user-images.githubusercontent.com/1457465/103316122-40a8de00-4a06-11eb-8810-6273c5aa43c0.png)

Checking both the image and the example images on GIMP, they seem to be using the exact same palette.

Does not seem to be an initialization problem, since if I replace the image with one of the demo images, it works:

![image](https://user-images.githubusercontent.com/1457465/103316271-bdd45300-4a06-11eb-9eb7-8f7fd03003b7.png)

Would this be a bug, or would there be some small little detail that I am missing?

**Comment by 8bit-Dude** [comment]
Hi Haroldo. I have checked the image and found the problem. 

While the 16 first colors are correct, the palette is actually 256 colors wide (with remaining colors assigned to white). I re-assigned the 16 colors lynx palette to image, and it works now.

Did you generate the image with your conversion script? If so, the code should ensure that palette is 16 colors wide.

![re-palettized](https://user-images.githubusercontent.com/6440924/103334176-cfbfff80-4ab3-11eb-99e9-f4921a7a7d40.png)

**Comment by haroldo-ok** [comment]
Thanks for the tip; I'll have to take a look at it later; one possible problem that could happen is that the version of PIL that comes with 8bit-Unity does not seem to support indexed images with less than 256 colors; not for writing, I mean.
