### ISSUE TITLE
Current 8-Bit Unity SDK download link is hard to script

### ISSUE THREAD

**Issue by seclorum** [8bit-Dude/8bit-Unity#3]
I'm setting up a Github Action to set up 8-bit Unity and build a project, automatically, as part of my project.

At the moment, the 8-bit Unity SDK is downloaded from this link:

https://dl.orangedox.com/8bit-Unity-0.3.5

This redirects to an 'orangebox' fileserving host which isn't compatible with wget.

This makes it difficult to create a .github/workflows/build-8bit-unity.yml file, i.e. create a Github build action that could be made available for devs to use in building a release, CI, etc.

Could some consideration be given to the idea of having the release .zip files made available on a wget-friendlier URL, i.e. even just on another repo set up specifically for 8-bit Unity asset releases?

**Comment by 8bit-Dude** [comment]
I have come up with a simple solution: uploading the entire toolchain and assets to GitHubs (including cc65 and Python).
You can now produce disks with the latest HEAD revision.

**Comment by seclorum** [comment]
Sorry to re-open this but I don't think this is quite as productive as one might assume .. are we to now generate the build scripts for the contents of the project/ folder manually, ourselves?  This kind of seems counter-intuitive to the idea that 8bit-Unity ships with example projects - and the _builder_.bat tool doesn't make things better, as it opens with no default configuration, and no real hints as to how to use it.  

I've spent 20  minutes trying to reproduce the original build/*oric*.bat scripts that were previously part of the 8bit-Unity redistributable, but I cannot reliably reproduce everything.

I think the tool is useful - for new 8bit-Unity projects, once developers have familiarized themselves with the way the projects layouts work - but to ship the demo's without a way to build them just makes it a bit harder to reproduce your work.

**Comment by 8bit-Dude** [comment]
.builder files are provided in the individual project folders, which will generate up-to-date scripts.
But for convenience, I will also upload the .bat scripts in /build folder of the repo.
