### ISSUE TITLE
Feature Request: make _builder_.bat functional from the command line ..

### ISSUE THREAD

**Issue by seclorum** [8bit-Dude/8bit-Unity#4]
It would be very useful (for example, in the case of an automated Github Action to build the projects) if the _builder_.bat file could accept a path on the command line arguments, to a ".builder" file, and then autogenerate the builder .BAT files for subsequent use in a project.

This way I could build a Github Action that runs _builder_.bat, generates the .bat files, runs the .bat files to compile the .DSK assets - all through Github, and thus not requiring a great deal of setup on the developer side.

**Comment by 8bit-Dude** [comment]
Alright, I have updated the builder so it can be called fro the command line.
Here is an example of call from the root of 8bit-Unity:
````
cd utils\scripts
..\py27\python builder.py -projectFile projects/dungeon/dungeon.builder -buildFolder .github -useGUI 0 -callEmu 0
````
Note 1: The paths for project file and build folders are relative to root of repo.
Note 2: Build folders directly under the root (e.g. 'build','.github') will work, sub-folders will not work (e.g. '.github/workflows').
